alias rr='ranger'

# cd dan list menggunakan function
cx() {cd "$@" && tree . ;}


#install sudo apt install
install() {sudo apt install "$@";}

# update apt
update() {sudo apt update;}

#nvim
alias nvim='~/Unduhan/nvim-linux64/bin/nvim' 


# sudo docker
alias dcin='sudo docker container inspect'
alias dcls='sudo docker container ls'
alias dclsa='sudo docker container ls -a'
alias dib='sudo docker image build'
alias dii='sudo docker image inspect'
alias dils='sudo docker image ls'
alias dipu='sudo docker image push'
alias dirm='sudo docker image rm'
alias dit='sudo docker image tag'
alias dlo='sudo docker container logs'
alias dnc='sudo docker network create'
alias dncn='sudo docker network connect'
alias dndcn='sudo docker network disconnect'
alias dni='sudo docker network inspect'
alias dnls='sudo docker network ls'
alias dnrm='sudo docker network rm'
alias dpo='sudo docker container port'
alias dpu='sudo docker pull'
alias dr='sudo docker container run'
alias drit='sudo docker container run -it'
alias drm='sudo docker container rm'
alias drs='sudo docker container restart'
alias dst='sudo docker container start'
alias dstp='sudo docker container stop'
alias dtop='sudo docker top'
alias dvi='sudo docker volume inspect'
alias dvls='sudo docker volume ls'
alias dvprune='sudo docker volume prune'
alias dxc='sudo docker container exec'
alias dxcit='sudo docker container exec -it'
alias dsta='sudo docker stop $(docker ps -q)'



# kubectl
alias k='sudo kubectl'
alias kaf='sudo kubectl apply -f'
alias kccc='sudo kubectl config current-context'
alias kcdc='sudo kubectl config delete-context'
alias kcgc='sudo kubectl config get-contexts'
alias kcn='sudo kubectl config set-context --current --namespace'
alias kcp='sudo kubectl cp'
alias kcsc='sudo kubectl config set-context'
alias kcuc='sudo kubectl config use-context'
alias kdcj='sudo kubectl describe cronjob'
alias kdcm='sudo kubectl describe configmap'
alias kdd='sudo kubectl describe deployment'
alias kdds='sudo kubectl describe daemonset'
alias kdel='sudo kubectl delete'
alias kdelcj='sudo kubectl delete cronjob'
alias kdelcm='sudo kubectl delete configmap'
alias kdeld='sudo kubectl delete deployment'
alias kdelds='sudo kubectl delete daemonset'
alias kdelf='sudo kubectl delete -f'
alias kdeli='sudo kubectl delete ingress'
alias kdelj='sudo kubectl delete job'
alias kdelno='sudo kubectl delete node'
alias kdelns='sudo kubectl delete namespace'
alias kdelp='sudo kubectl delete pods'
alias kdelpvc='sudo kubectl delete pvc'
alias kdels='sudo kubectl delete svc'
alias kdelsa='sudo kubectl delete sa'
alias kdelsec='sudo kubectl delete secret'
alias kdelss='sudo kubectl delete statefulset'
alias kdi='sudo kubectl describe ingress'
alias kdj='sudo kubectl describe job'
alias kdno='sudo kubectl describe node'
alias kdns='sudo kubectl describe namespace'
alias kdp='sudo kubectl describe pods'
alias kdpvc='sudo kubectl describe pvc'
alias kdrs='sudo kubectl describe replicaset'
alias kds='sudo kubectl describe svc'
alias kdsa='sudo kubectl describe sa'
alias kdsec='sudo kubectl describe secret'
alias kdss='sudo kubectl describe statefulset'
alias kecj='sudo kubectl edit cronjob'
alias kecm='sudo kubectl edit configmap'
alias ked='sudo kubectl edit deployment'
alias keds='sudo kubectl edit daemonset'
alias kei='sudo kubectl edit ingress'
alias kej='sudo kubectl edit job'
alias keno='sudo kubectl edit node'
alias kens='sudo kubectl edit namespace'
alias kep='sudo kubectl edit pods'
alias kepvc='sudo kubectl edit pvc'
alias kers='sudo kubectl edit replicaset'
alias kes='sudo kubectl edit svc'
alias kess='sudo kubectl edit statefulset'
alias keti='sudo kubectl exec -t -i'
alias kga='sudo kubectl get all'
alias kgaa='sudo kubectl get all --all-namespaces'
alias kgcj='sudo kubectl get cronjob'
alias kgcm='sudo kubectl get configmaps'
alias kgcma='sudo kubectl get configmaps --all-namespaces'
alias kgd='sudo kubectl get deployment'
alias kgda='sudo kubectl get deployment --all-namespaces'
alias kgds='sudo kubectl get daemonset'
alias kgdsa='sudo kubectl get daemonset --all-namespaces'
alias kgi='sudo kubectl get ingress'
alias kgia='sudo kubectl get ingress --all-namespaces'
alias kgj='sudo kubectl get job'
alias kgno='sudo kubectl get nodes'
alias kgns='sudo kubectl get namespaces'
alias kgp='sudo kubectl get pods'
alias kgpa='sudo kubectl get pods --all-namespaces'
alias kgpall='sudo kubectl get pods --all-namespaces -o wide'
alias kgpvc='sudo kubectl get pvc'
alias kgpvca='sudo kubectl get pvc --all-namespaces'
alias kgrs='sudo kubectl get replicaset'
alias kgs='sudo kubectl get svc'
alias kgsa='sudo kubectl get svc --all-namespaces'
alias kgsec='sudo kubectl get secret'
alias kgseca='sudo kubectl get secret --all-namespaces'
alias kgss='sudo kubectl get statefulset'
alias kgssa='sudo kubectl get statefulset --all-namespaces'
alias kl='sudo kubectl logs'
alias kl1h='sudo kubectl logs --since 1h'
alias kl1m='sudo kubectl logs --since 1m'
alias kl1s='sudo kubectl logs --since 1s'
alias klf='sudo kubectl logs -f'
alias klf1h='sudo kubectl logs --since 1h -f'
alias klf1m='sudo kubectl logs --since 1m -f'
alias klf1s='sudo kubectl logs --since 1s -f'
alias kpf='sudo kubectl port-forward'
alias krh='sudo kubectl rollout history'
alias krsd='sudo kubectl rollout status deployment'
alias krsss='sudo kubectl rollout status statefulset'
alias kru='sudo kubectl rollout undo'
alias ksd='sudo kubectl scale deployment'
alias ksss='sudo kubectl scale statefulset'


# Postman 
alias postman='cd ~/postman/Postman && ./Postman'

